spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/lms_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: LMSHikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Multipart File Configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MBasource:
    url: jdbc:mysql://localhost:3306/lms_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Jhansi@2003
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP settings
    hikari:
      pool-name: LMSHikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000   # 5 minutes
      max-lifetime: 1200000  # 20 minutes
      connection-timeout: 20000  # 20 seconds
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        
  # Server Configuration        
server:
  port: 8080
  servlet:
    context-path: /lms

# Logging Configuration
logging:
  level:
    com.lms: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
